apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app