@Library('ci-cd-library') _

cdPipeline(
    dockerRepo : 'yashwanthm998/todo-app',
    appVersion : '1.1.6',
    gitCommit  : 'abc1234',
    k8sCreds   : 'k8s-cred',
    k8sServer  : 'https://34.60.252.171'
)